<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员信息"
            }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"员工管理",
                       "menuJump":"列表",
                       "tableName":"yuangong"
                   }
               ],
               "menu":"员工管理"
           }
           ,{
               "child":[
                   {
                       "buttons":[
                           "查看",
                           "新增",
                           "修改",
                           "删除"
                       ],
                       "menu":"用户管理",
                       "menuJump":"列表",
                       "tableName":"yonghu"
                   }
               ],
               "menu":"用户管理"
           }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"材料管理",
                        "menuJump":"列表",
                        "tableName":"goods"
                    }
					,
					{
					    "buttons":[
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"材料出入库订单管理",
					    "menuJump":"列表",
					    "tableName":"inOutOrder"
					}
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"材料类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGoods"
                    }
                ],
                "menu":"材料管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"维修预约管理",
                        "menuJump":"列表",
                        "tableName":"weixiuyuyue"
                    }
                ],
                "menu":"维修预约管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"维修类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryWeixiuyuyue"
			        }
			
			    ],
			    "menu":"维修类型管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"材料管理",
	                    "menuJump":"列表",
	                    "tableName":"goods"
	                }
					,
					{
					    "buttons":[
					        "查看",
					        "修改",
					        "删除"
					    ],
					    "menu":"材料出入库订单管理",
					    "menuJump":"列表",
					    "tableName":"inOutOrder"
					}
	            ],
	            "menu":"材料管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "修改"
	                    ],
	                    "menu":"维修预约管理",
	                    "menuJump":"列表",
	                    "tableName":"weixiuyuyue"
	                }
	            ],
	            "menu":"维修预约管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"员工",
	    "tableName":"yuangong"
	}
	,
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"材料管理",
	                    "menuJump":"列表",
	                    "tableName":"goods"
	                }
	            ],
	            "menu":"材料管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改",
	                        "删除"
	                    ],
	                    "menu":"维修预约管理",
	                    "menuJump":"列表",
	                    "tableName":"weixiuyuyue"
	                }
	            ],
	            "menu":"维修预约管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"用户",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
